export const LeftMenuKeyConfig = [
  {
    menuId: 10,
    menuKey: "left-menu.batch-file",
    url: "/admin/batch-file",
    icon: "archive",
  },
  {
    menuId: 11,
    menuKey: "left-menu.result-reconcile",
    url: "/admin/paygate-financial-reconcile",
    icon: "library_books",
  },
  {
    menuId: 1101,
    menuKey: "left-menu.paygate-reconcile",
    url: "/admin/paygate-financial-reconcile",
    icon: "payment",
  },
  {
    menuId: 1102,
    menuKey: "left-menu.wallet-reconcile",
    url: "/admin/wallet-financial-reconcile",
    icon: "attach_money",
  },
  {
    menuId: 1103,
    menuKey: "left-menu.non-financial-reconcile",
    url: "/admin/non-financial-reconcile",
    icon: "money_off",
  },
  {
    menuId: 12,
    menuKey: "left-menu.report-reconcile",
    url: "/admin/reconcile-report",
    icon: "collections_bookmark",
  },
  {
    menuId: 1201,
    menuKey: "left-menu.report-overview",
    url: "/admin/reconcile-report",
    icon: "list_alt",
  },
  {
    menuId: 1202,
    menuKey: "left-menu.report-detail",
    url: "/admin/payment-transaction-report",
    icon: "verified_user",
  },
  {
    menuId: 1203,
    menuKey: "left-menu.transaction-payment-report",
    url: "/admin/payment-transaction-report",
    icon: "credit_card",
  },
  {
    menuId: 1204,
    menuKey: "left-menu.financial-report",
    url: "/admin/financial-transaction-report",
    icon: "attach_money",
  },
  {
    menuId: 1205,
    menuKey: "left-menu.non-financial-report",
    url: "/admin/non-financial-transaction-report",
    icon: "money_off",
  },
  {
    menuId: 1206,
    menuKey: "left-menu.non-financial-report",
    url: "/admin/non-financial-transaction-report",
    icon: "money_off",
  },
  {
    menuId: 13,
    menuKey: "left-menu.lookup-transaction",
    url: "/admin/lookup-transaction",
    icon: "youtube_searched_for_icon",
  },
  {
    menuId: 1301,
    menuKey: "left-menu.lookup-transaction-payment",
    url: "/admin/lookup-transaction-payment",
    icon: "payment_icon",
  },
  {
    menuId: 1302,
    menuKey: "left-menu.lookup-transaction-refund",
    url: "/admin/lookup-transaction-refund",
    icon: "monetization_on_icon",
  },
  {
    menuId: 14,
    menuKey: "left-menu.manager-Reconcile",
    url: "/admin/reconcile-manager",
    icon: "settings",
  },
];
export const FIXED_LEFT_MENU = [
  {
    url: "/admin/batch-file",
    actions: [],
    menu_id: 10,
    // children: [
    // ],
    menu_icon: "account balance wallet icon",
    mapped_url: '["/admin/batch-file"]',
    menu_level: 1,
    menu_title: "left-menu.batch-file",
  },
  {
    url: "/admin/lookup-transaction-payment",
    actions: [],
    menu_id: 13,
    children: [
      {
        url: "/admin/lookup-transaction-payment",
        actions: [],
        menu_id: 1301,
        // children: [
        // ],
        menu_icon: "payment icon",
        mapped_url: '["/admin/lookup-transaction-payment"]',
        menu_level: 2,
        menu_title: "left-menu.lookup-transaction-payment",
        menu_parent: 13,
      },
      {
        url: "/admin/lookup-transaction-refund",
        actions: [],
        menu_id: 1302,
        // children: [
        // ],
        menu_icon: "monetization on icon",
        mapped_url: '["/admin/lookup-transaction-refund"]',
        menu_level: 2,
        menu_title: "left-menu.wallet-reconcile",
        menu_parent: 13,
      },
    ],
    menu_icon: "youtube searched for icon",
    mapped_url: '["/admin/lookup-transaction"]',
    menu_level: 1,
    menu_title: "left-menu.lookup-transaction",
  },
  {
    url: "/admin/paygate-financial-reconcile",
    actions: [],
    menu_id: 11,
    children: [
      {
        url: "/admin/paygate-financial-reconcile",
        actions: [],
        menu_id: 1101,
        // children: [
        // ],
        menu_icon: "account balance wallet icon",
        mapped_url: '["/admin/paygate-financial-reconcile"]',
        menu_level: 2,
        menu_title: "left-menu.paygate-reconcile",
        menu_parent: 11,
      },
      {
        url: "/admin/wallet-financial-reconcile",
        actions: [],
        menu_id: 1102,
        // children: [
        // ],
        menu_icon: "account balance wallet icon",
        mapped_url: '["/admin/wallet-financial-reconcile"]',
        menu_level: 2,
        menu_title: "left-menu.wallet-reconcile",
        menu_parent: 11,
      },
      {
        url: "/admin/non-financial-reconcile",
        actions: [],
        menu_id: 1103,
        // children: [
        // ],
        menu_icon: "account balance wallet icon",
        mapped_url: '["/admin/non-financial-reconcile"]',
        menu_level: 2,
        menu_title: "left-menu.non-financial-reconcile",
        menu_parent: 11,
      },
    ],
    menu_icon: "account balance wallet icon",
    mapped_url: '["/admin/paygate-financial-reconcile"]',
    menu_level: 1,
    menu_title: "left-menu.result-reconcile",
  },
  {
    url: "/admin/reconcile-report",
    actions: [],
    menu_id: 12,
    children: [
      {
        url: "/admin/reconcile-report",
        actions: [],
        menu_id: 1201,
        // children: [
        // ],
        menu_icon: "account balance wallet icon",
        mapped_url: '["/admin/reconcile-report"]',
        menu_level: 2,
        menu_parent: 12,

        menu_title: "left-menu.report-overview",
      },
      {
        url: "/admin/payment-transaction-report",
        actions: [],
        menu_id: 1203,
        // children: [
        // ],
        menu_icon: "account balance wallet icon",
        mapped_url: '["/admin/payment-transaction-report"]',
        menu_level: 2,
        menu_parent: 12,
        menu_title: "left-menu.transaction-payment-report",
      },
      {
        url: "/admin/financial-transaction-report",
        actions: [],
        menu_id: 1204,
        // children: [
        // ],
        menu_icon: "account balance wallet icon",
        mapped_url: '["/admin/financial-transaction-report"]',
        menu_level: 2,
        menu_parent: 12,
        menu_title: "left-menu.financial-report",
      },
      {
        url: "/admin/non-financial-transaction-report",
        actions: [],
        menu_id: 1205,
        // children: [
        // ],
        menu_icon: "account balance wallet icon",
        mapped_url: '["/admin/non-financial-transaction-report"]',
        menu_level: 2,
        menu_parent: 12,
        menu_title: "left-menu.non-financial-report",
      },
    ],
    menu_icon: "account balance wallet icon",
    mapped_url: '["/admin/reconcile-report"]',
    menu_level: 1,
    menu_title: "left-menu.report-overview",
  },
];
