// for page title

const baseTitle = 'Tool vận hành đối soát';

export const TitleConstants = {
  BASE: baseTitle,
  LOGIN: `${baseTitle} | Login`,
  FISRTLOGIN: `${baseTitle} | Change password`,
  DASHBOARD: `${baseTitle} | Home`,
  PROFILE: `${baseTitle} | Profile`,
  USER: `${baseTitle} | User`,
  REGISTER: `${baseTitle} | Register`,
  FORGOT: `${baseTitle} | Forgot password`,
  RESETPW: `${baseTitle} | Reset password`,
  DEPARTMENT: `${baseTitle} | Department Management`,
  NOTIFICATION: `${baseTitle} | Notification`,
  TRANSACTION_PAYMENT: `${baseTitle} | Transaction Payment`,
  TRANSACTION_PAYMENT_DETAIL: `${baseTitle} | Transaction Payment Detail`,
  TRANSACTION_REFUND: `${baseTitle} | Transaction Refund`,
  TRANSACTION_REFUND_DETAIL: `${baseTitle} | Transaction Refund Detail`,
  SERVICE_INFOR_MANAGEMENT: `${baseTitle} | Service Infomation Management`,
  RISKS_MANAGEMENT_CARD: `${baseTitle} | Card Risk Management`,
  RISKS_MANAGEMENT_BIN: `${baseTitle} | BIN Range Risk Management`,
  RISKS_MANAGEMENT_TRANSACTION: `${baseTitle} | Transaction Risk Management`,
  RISKS_MANAGEMENT_ACCOUNT: `${baseTitle} | Account Risk Management`,
  RISKS_MANAGEMENT_OTHER: `${baseTitle} | Other Risk Management`,
  RISKS_MANAGEMENT_IP: `${baseTitle} | Ip Risk Management`,
  MERCHANT_PROFILE: `${baseTitle} | Merchant Profile`,
  SUB_MERCHANT: `${baseTitle} | Sub Merchant`,
  MERCHANT_QR: `${baseTitle} | QR Code`,
  STORE_PROFILE: `${baseTitle} | Store Profile`,
  SEARCH_PROFILE: `${baseTitle} | Search store`,
  STORE_DETAIL: `${baseTitle} | Store Detail`,
  REPORT: `${baseTitle} | Report`,
  ERROR: `${baseTitle} | Error`,
  E_WALLET: `${baseTitle} | E-Wallet`,
  WALLET_ACCOUNT: `${baseTitle} | Wallet Account`,
  WALLET_TRANSACTION: `${baseTitle} | Wallet Transaction`,
  PAYGATE_TRANSACTION: `${baseTitle} | Paygate Transaction`,
  RISKS_TRANSACTION: `${baseTitle} | Supicious Transaction`,
  SECURED_ACCOUNT: `${baseTitle} | Secured Account`,
  REVENUE_EXPENDITURE: `${baseTitle} | Collect-Pay Account`,
  WALLET_REPORT: `${baseTitle} | Wallet Report`,
  REVENUE_EXPENDITURE_REPORT: `${baseTitle} | Collect-Pay Report`,
  TRANSFER_REPORT: `${baseTitle} | Transfer Report`,
  PAYGATE_REPORT: `${baseTitle} | Paygate Report`,
  RISKS_MANAGEMENT: `${baseTitle} | Risk Management`,
  COLLECT_PAY: `${baseTitle} | Collect-Pay Management`,
  TRANSFER_TRANSACTION: `${baseTitle} | Transfer Transaction`,
  PAGE_NOT_FOUND: `${baseTitle} | Page Not Found`,
  BLOCK_TRANSACTION: `${baseTitle} | Block Transaction`,
};
